language: android

android:
  components:
  - build-tools-22.0.1
  - android-19
  - android-22
  - extra-android-support

branches:
  only:
    - master

notifications:
  email: false

script: './gradlew clean build'
