language: android

android:
  components:
  - build-tools-22.0.1
  - android-19

branches:
  only:
    - master

notifications:
  email: false

script: './gradlew clean build'

addons:
  coverity_scan:
    project:
        name: "Chrisplus/NFCSocket"
        description: "Android Play Near Flied Communication in the Socket way"
    build_command: "./gradlew clean build"
    branch_pattern: master